
dbt_airflow:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: dbt-postgres
      port: 5432
      user: admin
      pass: postgres
      dbname: dbt_demo_db
      schema: dev

  target: dev
